// Code generated by MockGen. DO NOT EDIT.
// Source: handler/wallet.go

// Package mockr is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIWalletHandler is a mock of IWalletHandler interface.
type MockIWalletHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIWalletHandlerMockRecorder
}

// MockIWalletHandlerMockRecorder is the mock recorder for MockIWalletHandler.
type MockIWalletHandlerMockRecorder struct {
	mock *MockIWalletHandler
}

// NewMockIWalletHandler creates a new mock instance.
func NewMockIWalletHandler(ctrl *gomock.Controller) *MockIWalletHandler {
	mock := &MockIWalletHandler{ctrl: ctrl}
	mock.recorder = &MockIWalletHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWalletHandler) EXPECT() *MockIWalletHandlerMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockIWalletHandler) CreateWallet(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateWallet", w, r)
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockIWalletHandlerMockRecorder) CreateWallet(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockIWalletHandler)(nil).CreateWallet), w, r)
}

// GetAllBalances mocks base method.
func (m *MockIWalletHandler) GetAllBalances(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAllBalances", w, r)
}

// GetAllBalances indicates an expected call of GetAllBalances.
func (mr *MockIWalletHandlerMockRecorder) GetAllBalances(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBalances", reflect.TypeOf((*MockIWalletHandler)(nil).GetAllBalances), w, r)
}

// GetBalance mocks base method.
func (m *MockIWalletHandler) GetBalance(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetBalance", w, r)
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockIWalletHandlerMockRecorder) GetBalance(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockIWalletHandler)(nil).GetBalance), w, r)
}

// UpdateWallet mocks base method.
func (m *MockIWalletHandler) UpdateWallet(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateWallet", w, r)
}

// UpdateWallet indicates an expected call of UpdateWallet.
func (mr *MockIWalletHandlerMockRecorder) UpdateWallet(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWallet", reflect.TypeOf((*MockIWalletHandler)(nil).UpdateWallet), w, r)
}
